@echo off
CHCP 65001 > nul
REM Script de Renombrado Automático para Windows (CMD)
ren "Barcelona.png" "FC_Barcelona.png"
ren "Sevilla.png" "Sevilla_FC.png"
ren "Villarreal.png" "Villarreal_CF.png"
ren "Valencia.png" "Valencia_CF.png"
ren "Osasuna.png" "CA_Osasuna.png"
ren "Espanyol.png" "RCD_Espanyol.png"
ren "Elche.png" "Elche_CF.png"
ren "Getafe.png" "Getafe_CF.png"
ren "Mallorca.png" "RCD_Mallorca.png"
ren "Levante.png" "Levante_UD.png"
ren "Girona.png" "Girona_FC.png"
ren "Real_Valladolid.png" "Valladolid.png"
ren "Real_Zaragoza.png" "Zaragoza.png"
ren "Granada.png" "Granada_CF.png"
ren "Cadiz.png" "Cadiz_CF.png"
ren "Burgos.png" "Burgos_CF.png"
ren "SD_Eibar.png" "Eibar.png"
ren "Malaga.png" "Malaga_CF.png"
ren "Cordoba.png" "Cordoba_CF.png"
ren "Albacete_Balompié.png" "Albacete.png"
ren "Andorra.png" "FC_Andorra.png"
ren "AD_Ceuta .png" "Ceuta.png"
ren "Arsenal.png" "Arsenal_FC.png"
ren "Chelsea.png" "Chelsea_FC.png"
ren "Liverpool.png" "Liverpool_FC.png"
ren "Bournemouth.png" "AFC_Bournemouth.png"
ren "Brentford.png" "Brentford_FC.png"
ren "Everton.png" "Everton_FC.png"
ren "Sunderland.png" "Sunderland_AFC.png"
ren "Fulham.png" "Fulham_FC.png"
ren "Leeds.png" "Leeds_United.png"
ren "Burnley.png" "Burnley_FC.png"
ren "Southampton.png" "Southampton_FC.png"
ren "Middlesbrough.png" "Middlesbrough_FC.png"
ren "Watford.png" "Watford_FC.png"
ren "Millwall.png" "Millwall_FC.png"
ren "Wrexham.png" "Wrexham_AFC.png"
ren "Portsmouth.png" "Portsmouth_FC.png"
ren "Juventus.png" "Juventus_de_Turin.png"
ren "Napoles.png" "SSC_Napoles.png"
ren "Milan.png" "AC_Milan.png"
ren "Roma.png" "AS_Roma.png"
ren "Como.png" "Como_1907.png"
ren "Lazio.png" "SS_Lazio.png"
ren "Torino.png" "Torino_FC.png"
ren "Sassuolo.png" "US_Sassuolo.png"
ren "Cremonese.png" "US_Cremonese.png"
ren "Lecce.png" "US_Lecce.png"
ren "Venezia.png" "Venezia_FC.png"
ren "Monza.png" "AC_Monza.png"
ren "Empoli.png" "Empoli_FC.png"
ren "Palermo.png" "Palermo_FC.png"
ren "Catanzaro.png" "US_Catanzaro.png"
ren "Cesena.png" "Cesena_FC.png"
ren "Modena.png" "Modena_FC.png"
ren "Sampdoria.png" "UC_Sampdoria.png"
ren "Juve_Stabia.png" "SS_Juve_Stabia.png"
ren "Leipzig.png" "RB_Leipzig.png"
ren "Stuttgart.png" "VfB_Stuttgart.png"
ren "Wolfsburgo.png" "VfL_Wolfsburgo.png"
ren "Werder_Bremen.png" "SV_Werder_Bremen.png"
ren "Hoffenheim.png" "TSG_1899_Hoffenheim.png"
ren "Friburgo.png" "SC_Friburgo.png"
ren "Mainz_05.png" "FSV_Mainz_05.png"
ren "Augsburgo.png" "FC_Augsburgo.png"
ren "Hamburgo.png" "Hamburgo_SV.png"
ren "Colonia.png" "FC_Colonia.png"
ren "St_Pauli.png" "FC_St_Pauli.png"
ren "Heidenheim.png" "FC_Heidenheim_1846.png"
ren "SpVgg_Greuther_Furth.png" "Greuther_Furth.png"
ren "SG_Dynamo_Dresden.png" "Dynamo_Dresden.png"
ren "Paris_Saint_Germain.png" "Paris_Saint_Germain_FC.png"
ren "Monaco.png" "AS_Monaco.png"
ren "Lille.png" "LOSC_Lille.png"
ren "Niza.png" "OGC_Niza.png"
ren "Stade_Rennais.png" "Stade_Rennais_FC.png"
ren "Paris.png" "Paris_FC.png"
ren "Toulouse.png" "Toulouse_FC.png"
ren "Stade_Brestois.png" "Stade_Brestois_29.png"
ren "Lens.png" "RC_Lens.png"
ren "Nantes.png" "FC_Nantes.png"
ren "Auxerre.png" "AJ_Auxerre.png"
ren "Lorient.png" "FC_Lorient.png"
ren "Metz.png" "FC_Metz.png"
ren "Le_Havre.png" "Le_Havre_AC.png"
ren "Angers.png" "Angers_SCO.png"
ren "Le_Mans.png" "Le_Mans_FC.png"
ren "Utrecht.png" "FC_Utrecht.png"
ren "Twente_Enschede.png" "FC_Twente_Enschede.png"
ren "Heerenveen.png" "SC_Heerenveen.png"
ren "Groningen.png" "FC_Groningen.png"
ren "Volendam.png" "FC_Volendam.png"
ren "Telstar.png" "SC_Telstar.png"
ren "VVV_Venlo.png" "VVV-Venlo.png"
ren "Oporto.png" "FC_Oporto.png"
ren "Benfica.png" "SL_Benfica.png"
ren "Braga.png" "SC_Braga.png"
ren "Famalicao.png" "FC_Famalicao.png"
ren "Rio_Ave.png" "Rio_Ave_FC.png"
ren "Santa_Clara.png" "CD_Santa_Clara.png"
ren "Estoril_Praia.png" "GD_Estoril_Praia.png"
ren "Alverca.png" "FC_Alverca.png"
ren "Gil_Vicente.png" "Gil_Vicente_FC.png"
ren "Casa_Pia.png" "Casa_Pia_AC.png"
ren "Moreirense.png" "Moreirense_FC.png"
ren "Vitoria_Guimaraes.png" "Vitoria_Guimaraes_SC.png"
ren "Arouca.png" "FC_Arouca.png"
ren "Tondela.png" "CD_Tondela.png"
ren "Estrela_Amadora.png" "CF_Estrela_Amadora.png"
ren "Academico_Viseu.png" "Academico_Viseu_FC.png"
ren "River_Plate.png" "CA_River_Plate.png"
ren "Boca_Juniors.png" "CA_Boca_Juniors.png"
ren "Independiente.png" "CA_Independiente.png"
ren "Estudiantes_de_La_Plata.png" "Club_Estudiantes_de_La_Plata.png"
ren "Talleres.png" "CA_Talleres.png"
ren "Rosario_Central.png" "CA_Rosario_Central.png"
ren "Argentinos_Juniors.png" "AA_Argentinos_Juniors.png"
ren "San_Lorenzo_de_Almagro.png" "CA_San_Lorenzo_de_Almagro.png"
ren "Belgrano.png" "CA_Belgrano.png"
ren "Godoy_Cruz_Antonio_Tomba.png" "CD_Godoy_Cruz_Antonio_Tomba.png"
ren "Tigre.png" "CA_Tigre.png"
ren "Defensa_y_Justicia.png" "CSD_Defensa_y_Justicia.png"
ren "Platense.png" "CA_Platense.png"
ren "CA_Unión.png" "CA_Unión_Santa_Fe.png"
ren "Independiente_Rivadavia.png" "CS_Independiente_Rivadavia.png"
ren "Barracas_Central.png" "CA_Barracas_Central.png"
ren "Newells_Old_Boys.png" "CA_Newells_Old_Boys.png"
ren "Central_Cordoba.png" "CA_Central_Cordoba_SdE.png"
ren "Banfield.png" "CA_Banfield.png"
ren "Sarmiento.png" "CA_Sarmiento_Junín.png"
ren "Aldosivi.png" "CA_Aldosivi.png"
ren "Palmeiras.png" "SE_Palmeiras.png"
ren "Flamengo.png" "CR_Flamengo.png"
ren "Corinthians.png" "SC_Corinthians.png"
ren "Athletic_Club.png" "Athletic_Club.png"

REM --- RESUMEN ---
echo. Renombrado 135 de 162 archivos.
echo. --- ATENCIÓN: CLUBES FALTANTES PENDIENTES ---
echo. ❌ FALTANTE: "Deportivo.png"
echo. ❌ FALTANTE: "Racing_Santander.png"
echo. ❌ FALTANTE: "Sporting_Gijon.png"
echo. ❌ FALTANTE: "Brighton_&_Hove_Albion.png"
echo. ❌ FALTANTE: "Wolverhampton_Wanderers.png"
echo. ❌ FALTANTE: "Atalanta_de_Bergamo.png"
echo. ❌ FALTANTE: "Pisa_Sporting_Club.png"
echo. ❌ FALTANTE: "Bayer_04_Leverkusen.png"
echo. ❌ FALTANTE: "Eintracht_Frankfurt.png"
echo. ❌ FALTANTE: "FC_Nuremberg.png"
echo. ❌ FALTANTE: "SV_Elversberg.png"
echo. ❌ FALTANTE: "Preussen_Munster.png"
echo. ❌ FALTANTE: "RC_Estrasburgo.png"
echo. ❌ FALTANTE: "Ajax_de_Amsterdam.png"
echo. ❌ FALTANTE: "CA_Vélez_Sarsfield.png"
echo. ❌ FALTANTE: "CA_Lanús.png"
echo. ❌ FALTANTE: "CA_Huracán.png"
echo. ❌ FALTANTE: "Club_Atlético_Tucumán.png"
echo. ❌ FALTANTE: "CA_San_Martín_San_Juan.png"
echo. ❌ FALTANTE: "Cruzeiro_Esporte_Clube.png"
echo. ❌ FALTANTE: "EC_Bahia.png"
echo. ❌ FALTANTE: "Atletico_Mineiro.png"
echo. ❌ FALTANTE: "Internacional.png"
echo. ❌ FALTANTE: "Sport_Recife.png"
echo. ❌ FALTANTE: "Ceara.png"
echo. ❌ FALTANTE: "EC_Vitoria.png"
echo. ❌ FALTANTE: "Juventude.png"
echo. --- ATENCIÓN: ARCHIVOS SOBRANTES PENDIENTES ---
echo. 🗑️ SOBRANTE: "Ajax.png" (Puede ser basura o un error de emparejamiento)
echo. 🗑️ SOBRANTE: "Atalanta.png" (Puede ser basura o un error de emparejamiento)
echo. 🗑️ SOBRANTE: "Bayer_Leverkusen.png" (Puede ser basura o un error de emparejamiento)
echo. 🗑️ SOBRANTE: "Brighton.png" (Puede ser basura o un error de emparejamiento)
echo. 🗑️ SOBRANTE: "Ceara_Sporting_Club.png" (Puede ser basura o un error de emparejamiento)
echo. 🗑️ SOBRANTE: "Clube_Atlético_Mineiro.png" (Puede ser basura o un error de emparejamiento)
echo. 🗑️ SOBRANTE: "Club_Atletico_Tucuman.png" (Puede ser basura o un error de emparejamiento)
echo. 🗑️ SOBRANTE: "Cruzeiro.png" (Puede ser basura o un error de emparejamiento)
echo. 🗑️ SOBRANTE: "Deportivo_de_La_Coruña.png" (Puede ser basura o un error de emparejamiento)
echo. 🗑️ SOBRANTE: "Eintracht_Francfort​​.png" (Puede ser basura o un error de emparejamiento)
echo. 🗑️ SOBRANTE: "Esporte_Clube_Bahia.png" (Puede ser basura o un error de emparejamiento)
echo. 🗑️ SOBRANTE: "Esporte_Clube_Juventude.png" (Puede ser basura o un error de emparejamiento)
echo. 🗑️ SOBRANTE: "Esporte_Clube_Vitoria.png" (Puede ser basura o un error de emparejamiento)
echo. 🗑️ SOBRANTE: "FC_Núremberg​.png" (Puede ser basura o un error de emparejamiento)
echo. 🗑️ SOBRANTE: "Huracan.png" (Puede ser basura o un error de emparejamiento)
echo. 🗑️ SOBRANTE: "Lanus.png" (Puede ser basura o un error de emparejamiento)
echo. 🗑️ SOBRANTE: "Pisa.png" (Puede ser basura o un error de emparejamiento)
echo. 🗑️ SOBRANTE: "Preußen_Munster.png" (Puede ser basura o un error de emparejamiento)
echo. 🗑️ SOBRANTE: "Racing_Club_de_Estrasburgo.png" (Puede ser basura o un error de emparejamiento)
echo. 🗑️ SOBRANTE: "Real_Racing_Club.png" (Puede ser basura o un error de emparejamiento)
echo. 🗑️ SOBRANTE: "Real_Sporting_de_Gijon.png" (Puede ser basura o un error de emparejamiento)
echo. 🗑️ SOBRANTE: "San Martín.png" (Puede ser basura o un error de emparejamiento)
echo. 🗑️ SOBRANTE: "Sport_Club_do_Recife.png" (Puede ser basura o un error de emparejamiento)
echo. 🗑️ SOBRANTE: "Sport_Club_Internacional.png" (Puede ser basura o un error de emparejamiento)
echo. 🗑️ SOBRANTE: "SV_07_Elversberg.png" (Puede ser basura o un error de emparejamiento)
echo. 🗑️ SOBRANTE: "Velez_Sarsfield.png" (Puede ser basura o un error de emparejamiento)
echo. 🗑️ SOBRANTE: "Wolverhampton.png" (Puede ser basura o un error de emparejamiento)